name: envcroco

channels:
  - conda-forge
  - nodefaults

dependencies:
  - cartopy==0.21.0
  - geopandas==0.11.1
  - matplotlib-base==3.6.0
  - netcdf4==1.6.1
  - numpy==1.23.4
  - python==3.9.13
  - regionmask==0.9.0
  - scipy==1.9.1
  - shapely==1.8.4
  - xarray==2022.11.0

  # WX dependancies
  - traits==6.4.1
  - traitsui==7.4.0
  - wxpython==4.1.1

  # Jupyterlab dependancies
  - jupyterlab==3.5.3
  - ipympl==0.9.2
  - ipywidgets==8.0.3
