name: envcroco

channels:
  - conda-forge
  - defaults

dependencies:
  - cartopy
  - dask
  - geopandas
  - matplotlib-base
  - netcdf4
  - numpy
  - python=3.9
  - regionmask
  - scipy
  - traits
  - traitsui
  - wxpython
  - xarray
