
pages:
  tags:
    - ci.inria.fr
  image: python:3.9
  before_script:
      - pip install --upgrade pip
      - pip install -r doc/requirements.txt
      - apt-get update && apt-get install -y curl  
  script:
    - |
      if [ "$CI_COMMIT_REF_NAME" = "release" ]; then
        # for release, directly in public
        sphinx-build -b html doc public
      else
        curl --verbose --location --output artifacts.zip --header "JOB-TOKEN:$CI_JOB_TOKEN" "https://gitlab.inria.fr/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/release/download?job=pages"
        # unzip last build
        unzip artifacts.zip
        # adding branch build
        sphinx-build -b html doc public/dev
      fi
  artifacts:
    paths:
      - public
    when: always
    expire_in: 1 day

