name: envtest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib-base
  - scipy
  - cartopy
  - wxpython
  - traits
  - traitsui
  - netcdf4
  - dask
  - xarray
  - geopandas
  - regionmask
